language: php

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6

before_script:
    - COMPOSER_ROOT_VERSION=dev-master composer --prefer-dist install

script:
  - vendor/bin/phpunit -v
